#!/usr/bin/env node

// Utility script to generate SN (Sub 8) prompts from words.js
// This script reads all words, finds prompts that have 8 or fewer solutions,
// and exports them to data/sn.js

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read words.js file
const wordsPath = path.join(__dirname, '../data/words.js');
const wordsContent = fs.readFileSync(wordsPath, 'utf8');

// Extract words array from words.js (it's a default export on one line)
const wordsMatch = wordsContent.match(/export default \[(.*)\]/s);
if (!wordsMatch) {
  console.error('Could not find words array in words.js');
  process.exit(1);
}

const wordsString = wordsMatch[1];
const words = wordsString.split('","').map(word => word.trim().replace(/^["']|["']$/g, ''));

console.log(`Loaded ${words.length} words`);

// Function to find all prompts that appear in words
function findAllPrompts(words) {
  const promptCounts = {};
  
  for (const word of words) {
    const upperWord = word.toUpperCase();
    
    // Check all possible substrings of length 2-3
    for (let len = 2; len <= 3; len++) {
      for (let i = 0; i <= upperWord.length - len; i++) {
        const prompt = upperWord.substring(i, i + len);
        
        // Only consider valid letter combinations (all letters)
        if (/^[A-Z]+$/.test(prompt)) {
          promptCounts[prompt] = (promptCounts[prompt] || 0) + 1;
        }
      }
    }
  }
  
  return promptCounts;
}

// Generate all prompts and their solution counts
console.log('Finding all prompts...');
const allPrompts = findAllPrompts(words);
console.log(`Found ${Object.keys(allPrompts).length} unique prompts`);

// Filter for sub8 prompts (8 or fewer solutions)
const sub8Prompts = [];
for (const [prompt, count] of Object.entries(allPrompts)) {
  if (count <= 8) {
    sub8Prompts.push([prompt, count]);
  }
}

// Sort by solution count (descending) then by prompt
sub8Prompts.sort((a, b) => {
  if (b[1] !== a[1]) return b[1] - a[1]; // Higher count first
  return a[0].localeCompare(b[0]); // Alphabetical
});

console.log(`Found ${sub8Prompts.length} sub8 prompts`);

// Generate the sn.js file content
const snContent = `// SN (Sub 8) Prompts - prompts with 8 or fewer solutions
// Generated by utility/generateSN.js
// Format: [prompt, solutionCount]

export const SN_PROMPTS = [
${sub8Prompts.map(([prompt, count]) => `  ["${prompt}", ${count}]`).join(',\n')}
];

export const SN_PROMPTS_LIST = SN_PROMPTS;

// For compatibility with existing code
export const SN_PROMPTS_RAW = Object.fromEntries(SN_PROMPTS);
`;

// Write to data/sn.js
const outputPath = path.join(__dirname, '../data/sn.js');
fs.writeFileSync(outputPath, snContent);

console.log(`Generated ${sub8Prompts.length} sub8 prompts in data/sn.js`);
console.log('Done!');
